name: Build Window Packer Image

on:
  push:
    branches:
      - cem/runnerimage

# defaults:
#   run:
#     shell: pwsh

jobs:
  packer:
    runs-on: windows-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #   - name: BuildAgentIP
      #     id: BuildAgentIP
      #     run: |
      #       $ipaddress = Invoke-RestMethod -Uri "http://ipinfo.io/ip"
      #       Write-Output "::set-output name=address::$ipaddress"

      - name: packer build
        run: |
          cd images/windows/templates
          packer init ./windows-2022.pkr.hcl
          packer validate ./windows-2022.pkr.hcl
          packer build  -debug ./windows-2022.pkr.hcl
        env:
          # ARM_CLIENT_CERT_PATH: ${{ secrets.ARM_CLIENT_CERT_PATH }}
          ARM_CLIENT_ID: "52563be7-6764-4964-b3dc-beb18e7623d2"
          ARM_CLIENT_SECRET: ~H48Q~tiI1SZXH~GNq8SdqSI_9yXS124.GjHNb8Q
          IMAGE_VERSION: ${{ env.GITHUB_RUN_ID }}-dev
          # ARM_RESOURCE_LOCATION: ${{ secrets.ARM_RESOURCE_LOCATION }}
          ARM_RESOURCE_GROUP: "ETN-POC-VTD-RUNNER"
          ARM_SUBSCRIPTION_ID: 9013acaf-d6cc-4416-a9ed-7075ba759979
          ARM_TENANT_ID: d6525c95-b906-431a-b926-e9b51ba43cc4
          BUILD_RESOURCE_GROUP_NAME: "ETN-POC-VTD-RUNNER"
          # TEMP_RESOURCE_GROUP_NAME: ${{ secrets.TEMP_RESOURCE_GROUP_NAME }}
          #   ALLOWED_INBOUND_IP_ADRESSES: ${{ steps.BuildAgentIP.outputs.address }}
          VNET_NAME: ${{ secrets.VNET_NAME }}
          VNET_RESOURCE_GROUP: ${{ secrets.VNET_RESOURCE_GROUP }}
          VNET_SUBNET: ${{ secrets.VNET_SUBNET }}
          GALLERY_NAME: "pakcercem"
